// <auto-generated />
using Eshop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251002172037_ReseedProductsImg")]
    partial class ReseedProductsImg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Eshop.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/motherboards.jpg",
                            Name = "Motherboards"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supplies"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cases.jpg",
                            Name = "Cases"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitors.jpg",
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripherals.jpg",
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 100,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/uncategorized.jpg",
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High performance CPU model 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 1",
                            Price = 220m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High performance CPU model 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 2",
                            Price = 240m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "High performance CPU model 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 3",
                            Price = 260m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "High performance CPU model 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 4",
                            Price = 280m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "High performance CPU model 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 5",
                            Price = 300m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "High performance CPU model 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 6",
                            Price = 320m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "High performance CPU model 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 7",
                            Price = 340m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "High performance CPU model 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 8",
                            Price = 360m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "High performance CPU model 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 9",
                            Price = 380m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "High performance CPU model 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU 10",
                            Price = 400m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 1",
                            Price = 165m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 2",
                            Price = 180m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 3",
                            Price = 195m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 4",
                            Price = 210m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 5",
                            Price = 225m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 6",
                            Price = 240m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 7",
                            Price = 255m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 8",
                            Price = 270m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 9",
                            Price = 285m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Reliable motherboard model 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/mb.jpg",
                            Name = "Motherboard 10",
                            Price = 300m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Powerful graphics card 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 1",
                            Price = 450m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Powerful graphics card 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 2",
                            Price = 500m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Powerful graphics card 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 3",
                            Price = 550m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Powerful graphics card 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 4",
                            Price = 600m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Powerful graphics card 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 5",
                            Price = 650m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Powerful graphics card 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 6",
                            Price = 700m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Powerful graphics card 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 7",
                            Price = 750m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Powerful graphics card 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 8",
                            Price = 800m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Powerful graphics card 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 9",
                            Price = 850m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Powerful graphics card 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU 10",
                            Price = 900m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 1",
                            Price = 75m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 2",
                            Price = 80m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 3",
                            Price = 85m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 4",
                            Price = 90m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 5",
                            Price = 95m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 6",
                            Price = 100m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 7",
                            Price = 105m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 8",
                            Price = 110m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 9",
                            Price = 115m,
                            Quantity = 19
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Fast DDR memory kit 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM 10",
                            Price = 120m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 1",
                            Price = 100m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 2",
                            Price = 110m,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 3",
                            Price = 120m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 4",
                            Price = 130m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 5",
                            Price = 140m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 6",
                            Price = 150m,
                            Quantity = 26
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 7",
                            Price = 160m,
                            Quantity = 27
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 8",
                            Price = 170m,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 9",
                            Price = 180m,
                            Quantity = 29
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "Reliable SSD/HDD 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage 10",
                            Price = 190m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            Description = "Stable PSU unit 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 1",
                            Price = 90m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            Description = "Stable PSU unit 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 2",
                            Price = 100m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            Description = "Stable PSU unit 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 3",
                            Price = 110m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            Description = "Stable PSU unit 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 4",
                            Price = 120m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Description = "Stable PSU unit 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 5",
                            Price = 130m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Description = "Stable PSU unit 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 6",
                            Price = 140m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Description = "Stable PSU unit 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 7",
                            Price = 150m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Description = "Stable PSU unit 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 8",
                            Price = 160m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            Description = "Stable PSU unit 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 9",
                            Price = 170m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            Description = "Stable PSU unit 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supply 10",
                            Price = 180m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            Description = "Durable PC case 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 1",
                            Price = 65m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            Description = "Durable PC case 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 2",
                            Price = 70m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            Description = "Durable PC case 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 3",
                            Price = 75m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            Description = "Durable PC case 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 4",
                            Price = 80m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            Description = "Durable PC case 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 5",
                            Price = 85m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            Description = "Durable PC case 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 6",
                            Price = 90m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            Description = "Durable PC case 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 7",
                            Price = 95m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            Description = "Durable PC case 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 8",
                            Price = 100m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            Description = "Durable PC case 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 9",
                            Price = 105m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            Description = "Durable PC case 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/case.jpg",
                            Name = "Case 10",
                            Price = 110m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 1",
                            Price = 55m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 2",
                            Price = 60m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 3",
                            Price = 65m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 4",
                            Price = 70m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 5",
                            Price = 75m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 6",
                            Price = 80m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 7",
                            Price = 85m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 8",
                            Price = 90m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 9",
                            Price = 95m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 8,
                            Description = "Efficient cooling solution 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling 10",
                            Price = 100m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            Description = "High-resolution monitor 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 1",
                            Price = 230m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 9,
                            Description = "High-resolution monitor 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 2",
                            Price = 260m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 9,
                            Description = "High-resolution monitor 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 3",
                            Price = 290m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 9,
                            Description = "High-resolution monitor 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 4",
                            Price = 320m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 9,
                            Description = "High-resolution monitor 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 5",
                            Price = 350m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 9,
                            Description = "High-resolution monitor 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 6",
                            Price = 380m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 9,
                            Description = "High-resolution monitor 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 7",
                            Price = 410m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            Description = "High-resolution monitor 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 8",
                            Price = 440m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 9,
                            Description = "High-resolution monitor 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 9",
                            Price = 470m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 9,
                            Description = "High-resolution monitor 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitor.jpg",
                            Name = "Monitor 10",
                            Price = 500m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 10,
                            Description = "Peripheral device 1",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 1",
                            Price = 40m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 10,
                            Description = "Peripheral device 2",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 2",
                            Price = 50m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 10,
                            Description = "Peripheral device 3",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 3",
                            Price = 60m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 10,
                            Description = "Peripheral device 4",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 4",
                            Price = 70m,
                            Quantity = 19
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 10,
                            Description = "Peripheral device 5",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 5",
                            Price = 80m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 10,
                            Description = "Peripheral device 6",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 6",
                            Price = 90m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 10,
                            Description = "Peripheral device 7",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 7",
                            Price = 100m,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 10,
                            Description = "Peripheral device 8",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 8",
                            Price = 110m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 10,
                            Description = "Peripheral device 9",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 9",
                            Price = 120m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 10,
                            Description = "Peripheral device 10",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripheral.jpg",
                            Name = "Peripheral 10",
                            Price = 130m,
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.HasOne("Eshop.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Eshop.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
