// <auto-generated />
using Eshop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251002161035_UpdateImageUrls")]
    partial class UpdateImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Eshop.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/motherboards.jpg",
                            Name = "Motherboards"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Power Supplies"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cases.jpg",
                            Name = "Cases"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Cooling"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitors.jpg",
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripherals.jpg",
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 100,
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/uncategorized.jpg",
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High-performance gaming CPU",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cpu.jpg",
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 399.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Gaming motherboard with PCIe 5.0",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/motherboards.jpg",
                            Name = "ASUS ROG Strix B650-E",
                            Price = 249.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "High-end graphics card",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/gpu.jpg",
                            Name = "NVIDIA RTX 4080",
                            Price = 1199.99m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Fast DDR5 RAM kit",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/ram.jpg",
                            Name = "Corsair Vengeance 32GB DDR5",
                            Price = 149.99m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "High-speed NVMe storage",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/storage.jpg",
                            Name = "Samsung 980 Pro 1TB NVMe SSD",
                            Price = 109.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "80+ Gold certified PSU",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/psu.jpg",
                            Name = "Corsair RM850x 850W PSU",
                            Price = 129.99m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Compact ATX case",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cases.jpg",
                            Name = "NZXT H510 Case",
                            Price = 79.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Air cooler for CPUs",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/cooling.jpg",
                            Name = "Noctua NH-D15 Cooler",
                            Price = 99.99m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "4K IPS monitor",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/monitors.jpg",
                            Name = "Dell Ultrasharp 27\"",
                            Price = 499.99m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Description = "Mechanical gaming keyboard",
                            ImageUrl = "https://raw.githubusercontent.com/B0husk0/Eshop/main/assets/images/peripherals.jpg",
                            Name = "Logitech G Pro X Keyboard",
                            Price = 129.99m,
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.HasOne("Eshop.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Eshop.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
