// <auto-generated />
using Eshop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250928155658_AddUncategorizedCategory")]
    partial class AddUncategorizedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Eshop.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://via.placeholder.com/150?text=CPU",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://via.placeholder.com/150?text=Motherboards",
                            Name = "Motherboards"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://via.placeholder.com/150?text=GPU",
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://via.placeholder.com/150?text=RAM",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://via.placeholder.com/150?text=Storage",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://via.placeholder.com/150?text=PSU",
                            Name = "Power Supplies"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://via.placeholder.com/150?text=Cases",
                            Name = "Cases"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://via.placeholder.com/150?text=Cooling",
                            Name = "Cooling"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://via.placeholder.com/150?text=Monitors",
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://via.placeholder.com/150?text=Peripherals",
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 100,
                            ImageUrl = "https://via.placeholder.com/150?text=Uncategorized",
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High-performance gaming CPU",
                            ImageUrl = "https://picsum.photos/seed/cpu/600/400",
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 399.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Gaming motherboard with PCIe 5.0",
                            ImageUrl = "https://picsum.photos/seed/motherboard/600/400",
                            Name = "ASUS ROG Strix B650-E",
                            Price = 249.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "High-end graphics card",
                            ImageUrl = "https://picsum.photos/seed/gpu/600/400",
                            Name = "NVIDIA RTX 4080",
                            Price = 1199.99m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Fast DDR5 RAM kit",
                            ImageUrl = "https://picsum.photos/seed/ram/600/400",
                            Name = "Corsair Vengeance 32GB DDR5",
                            Price = 149.99m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "High-speed NVMe storage",
                            ImageUrl = "https://picsum.photos/seed/ssd/600/400",
                            Name = "Samsung 980 Pro 1TB NVMe SSD",
                            Price = 109.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "80+ Gold certified PSU",
                            ImageUrl = "https://picsum.photos/seed/psu/600/400",
                            Name = "Corsair RM850x 850W PSU",
                            Price = 129.99m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Compact ATX case",
                            ImageUrl = "https://picsum.photos/seed/case/600/400",
                            Name = "NZXT H510 Case",
                            Price = 79.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Air cooler for CPUs",
                            ImageUrl = "https://picsum.photos/seed/cooler/600/400",
                            Name = "Noctua NH-D15 Cooler",
                            Price = 99.99m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "4K IPS monitor",
                            ImageUrl = "https://picsum.photos/seed/monitor/600/400",
                            Name = "Dell Ultrasharp 27\"",
                            Price = 499.99m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Description = "Mechanical gaming keyboard",
                            ImageUrl = "https://picsum.photos/seed/keyboard/600/400",
                            Name = "Logitech G Pro X Keyboard",
                            Price = 129.99m,
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("Eshop.Api.Models.Product", b =>
                {
                    b.HasOne("Eshop.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Eshop.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
