name: Build and deploy ASP.Net Core app to Azure Web App - eshop-api-a

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Eshop.Api/Eshop.Api.csproj

      - name: Build with dotnet
        run: dotnet build Eshop.Api/Eshop.Api.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish Eshop.Api/Eshop.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4F2BDA6CC4FE40649E1BE943DB1361F2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0586B30442D84A7688F7BD928D04A273 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AFF03F8B6FCC40D4AB97DB90FEB0408A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eshop-api-a'
          slot-name: 'Production'
          package: ${{ github.workspace }}/.net-app

